In [1]:
import pandas as pd
import numpy as np

In [2]:
## import datasets

df = pd.read_csv("insurance.csv")

#### Pertanyaan 1 - Kovarians dan korelasi antara variable charges dan bmi

In [3]:
df[['charges', 'bmi']].corr()

charges       bmi
charges  1.000000  0.198341
bmi      0.198341  1.000000

In [4]:
np.cov(df["charges"], df['bmi'])

array([[1.46652372e+08, 1.46473044e+04],
       [1.46473044e+04, 3.71878836e+01]])

#### Pertanyaan 2 - Kovarians dan korelasi antara variable charges dan smoker

In [5]:
df["smoker_code"] = df["smoker"].map({"yes": 1, "no": 0})
df[["smoker", "smoker_code"]][30:35]

smoker  smoker_code
30    yes            1
31     no            0
32     no            0
33     no            0
34    yes            1

In [6]:
np.cov(df["charges"], df["smoker_code"])

array([[1.46652372e+08, 3.84866703e+03],
       [3.84866703e+03, 1.62968876e-01]])

In [7]:
df[['charges', 'smoker_code']].corr()

charges  smoker_code
charges      1.000000     0.787251
smoker_code  0.787251     1.000000

#### Pertanyaan 3 - Kovarians dan korelasi antara variable bmi dan sex

In [20]:
np.cov(df["bmi"], df["smoker_code"])

array([[3.71878836e+01, 9.23280485e-03],
       [9.23280485e-03, 1.62968876e-01]])

In [9]:
df[['bmi', 'smoker_code']].corr()

bmi  smoker_code
bmi          1.00000      0.00375
smoker_code  0.00375      1.00000

#### Pertanyaan 4 - Kovarians dan korelasi antara variable charges dan sex 

In [14]:
df["gender_codes"] = df["sex"].map({"female": 1, "male": 0})

df[["sex", "gender_codes"]][10:15]

sex  gender_codes
10    male             0
11  female             1
12    male             0
13  female             1
14    male             0

In [15]:
np.cov(df["charges"], df["gender_codes"])

array([[ 1.46652372e+08, -3.47014469e+02],
       [-3.47014469e+02,  2.50159595e-01]])

In [16]:
df[["charges", "gender_codes"]].corr()

charges  gender_codes
charges       1.000000     -0.057292
gender_codes -0.057292      1.000000

#### Pertanyaan 5 - Kovarians dan korelasi antara variable charges dan age 

In [17]:
np.cov(df["charges"], df["age"])

array([[1.46652372e+08, 5.08748023e+04],
       [5.08748023e+04, 1.97401387e+02]])

In [19]:
df[["charges", "age"]].corr()

charges       age
charges  1.000000  0.299008
age      0.299008  1.000000